<<<<<<< HEAD
title: Balanced: Blog
=======
title: "Balanced: Blog"
>>>>>>> d0f42d1255e8b2346326d1a467c277ae6a9da753
#url: http://www.mydomain.com

markdown: maruku
pygments: true
permalink: /:title

lsi: true
paginate: 20

exclude:
- CNAME
